version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
    - run:
        command: |
          mkdir build
          echo 'wawawa' >> build/wawawa.txt

    - persist_to_workspace:
        root: ~/repo/build
        paths:
            - build/* 
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
    - attach_workspace:
        at: ~/repo
    - run:
        command: |
          ls -l 
          ls -l build 

workflows:
   main:
     jobs:
     - build 
     - deploy:
         requires:
           - build
