version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:lts
    working_directory: ~/repo
    steps:
    - run:
        command: |
          run: echo 'wawawa' >> /build/wawawa.txt
    - persist_to_workspace:
        root: ~/repo
        paths:
            - build/* 
  deploy:
    docker:
      - image: circleci/python:lts
    steps:
    - attach_workspace:
        at: ~/repo
    - run:
        command: |
          ls -l 
          ls -l build 

workflows:
   main:
     jobs:
     - build 
     - deploy:
         requires:
           - build
